### ISSUE TITLE
useDarkMode: default light theme causing flickers when switching stories

### ISSUE THREAD

**Issue by Clarity-89** [hipstersmoothie/storybook-dark-mode#109]
`useDarkMode` hook has the theme set to `light` [by default](https://github.com/hipstersmoothie/storybook-dark-mode/blob/master/src/index.tsx#L9). As result on the first render the mode is set to `light`, which is then updated via the channel. This causes noticeable theme flickers in dark mode in stories with slow loading times, for example the ones [loaded via iframes](https://github.com/grafana/grafana/issues/24996#issuecomment-632575330). 

Since the current theme value is already saved to local storage and used in the `DarkMode` [tool](https://github.com/hipstersmoothie/storybook-dark-mode/blob/master/src/Tool.tsx#L88), the same store can be used to populate the initial state for the `useDarkMode` hook.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v0.6.1`](https://github.com/hipstersmoothie/storybook-dark-mode/releases/tag/v0.6.1) :rocket:
