### ISSUE TITLE
Instructions don't match current storybook configuration files

### ISSUE THREAD

**Issue by gimbo** [hipstersmoothie/storybook-dark-mode#125]
This isn't a blocker for me, but I thought you might like to know that your installation/configuration instructions don't correspond with the files found in a fresh storybook installation, or in the current introductory docs.

---

I'm just starting using storybook, so I've been following the [introductory docs on storybook.js.org](https://storybook.js.org/docs/react/get-started/introduction); there, the [section on Configuration](https://storybook.js.org/docs/react/configure/overview) describes files matching my shiny new storybook install, e.g. and in particular I have a `main.js`, and no `config.js` ([apparently](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78) this is a relatively recent development?).

storybook-dark-mode's installation instructions, however, refer to `addons.js` and `config.js`.

I figured out that instead of `addons.js`, I can just add `'storybook-dark-mode'` to the `addons` list in `main.js`, so I've got the addon working — excellent! (And thanks.)

However, I if I try to create a `config.js` as shown in the "Configuration" section, storybook won't start (it doesn't allow both `main.js` and `config.js` to coexist), and it's not clear to me at all how to modify the suggested configuration for use with `main.js`.

Again, this isn't a blocker for me, as I'm happy enough with a simple light/dark toggle, but I thought you might like to know about this potential confusion for new users.

Thanks again for a cool and useful addon.

**Comment by hipstersmoothie** [comment]
I think i've updated the docs enough help you out. Feel free to open another issue if you run into further problems!

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.4`](https://github.com/hipstersmoothie/storybook-dark-mode/releases/tag/v1.0.4) :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.4`](https://github.com/hipstersmoothie/storybook-dark-mode/releases/tag/v1.0.4) :rocket:
