### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by alexbleggi** [hipstersmoothie/storybook-dark-mode#130]
Hello Guys!!!

I'd like to know if it's possible to implement this addon using Angular???

Thanks!!!

**Comment by hipstersmoothie** [comment]
I don't see why you wouldn't be able to use this in an angular project. if you encounter any problems post about theme here! I like pull requests too

**Comment by yusijs** [comment]
I'm using it with Angular, works perfectly fine.

**Comment by dsimon-onventis** [comment]
In case you are using Angular Material with [angular-material-css-vars](https://github.com/johannesjo/angular-material-css-vars), you can set it up in your `preview.js` like the following:

```
import addons from '@storybook/addons';
const channel = addons.getChannel();

export const decorators = [
  moduleMetadata({
    imports: [MaterialCssVarsModule.forRoot()],
    providers: [
      {
        provide: APP_INITIALIZER,
        useFactory: (materialCssVarsService) => () => {
          channel.addListener('DARK_MODE', isDark => materialCssVarsService.setDarkTheme(isDark));
        },
        deps: [MaterialCssVarsService],
        multi: true
      },
    ],
  }),
];
```
