### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by zitooo** [hipstersmoothie/storybook-dark-mode#132]
Hello. I don't know if I missed anything, but I'm getting this error when running `npm run storybook` after installing storybook-dark-mode:
![Captura de tela de 2021-01-07 14-49-48](https://user-images.githubusercontent.com/8508044/103926403-a3316680-50f7-11eb-8cf7-5a8ac8160047.png)

Here are the steps:
1. I created a new project with next.js: `npx create-next-app project-test`
2. Inside it, I installed the Storybook: `npx sb init`
3. Then I installed the storybook-dark-mode: `npm i --save-dev storybook-dark-mode`
4. And, inside .storybook / main.js, I added: `presets: ['storybook-dark-mode']`

![Captura de tela de 2021-01-07 14-54-06](https://user-images.githubusercontent.com/8508044/103926860-48e4d580-50f8-11eb-83f4-74e8cde2b0f7.png)

Thank you very much in advance!

**Comment by dricholm** [comment]
I was getting the same and managed to fix this by adding it to addons instead of presets in .storybook/preview.js:

```js
module.exports = {
  addons: [
    // ...
    'storybook-dark-mode',
  ],
};
```

This could be a change in Storybook v6, I have not really used it before. In that case maybe the README should be updated to match this.

**Comment by zitooo** [comment]
This is not working for me ... 
Including the code above, I get the following error: 
![Captura de tela de 2021-01-13 17-05-45](https://user-images.githubusercontent.com/8508044/104505467-b72b0b80-55c2-11eb-84df-3b1eb41ab7b0.png)

Using ES Modules syntax the error disappears:
`export default {
  addons: [
    'storybook-dark-mode',
  ],
};`

But the button to switch the mode is not shown:
![Captura de tela de 2021-01-13 17-15-19](https://user-images.githubusercontent.com/8508044/104505637-f8232000-55c2-11eb-8b35-9f55e253b338.png)

**Comment by dricholm** [comment]
@zitooo I accidentally typed `preview.js` in the previous comment. It should be `main.js`. Can you try it with that?
Sorry about the mistake.

**Comment by zitooo** [comment]
Perfect! Now yes!
Thank you very much @dricholm!
