### ISSUE TITLE
Unmet peerDependencies only for `storybook-dark-mode`

### ISSUE THREAD

**Issue by emattias** [hipstersmoothie/storybook-dark-mode#183]
<img width="775" alt="CleanShot 2022-05-05 at 12 57 40@2x" src="https://user-images.githubusercontent.com/351537/166909930-65de73a3-6d27-425b-b5e4-043fd0433468.png">

We have a couple of storybook addons installed and only get the `unmet peer dependency` for `storybook-dark-mode`. Could they be removed or maybe be made optional like  [@storybook/addon-*](https://github.com/storybookjs/storybook/blob/v6.4.22/addons/a11y/package.json#L73-L80) do?

**Comment by hipstersmoothie** [comment]
fix in above PR
