### ISSUE TITLE
classTarget not updating preview node in storybook v7

### ISSUE THREAD

**Issue by redonkulus** [hipstersmoothie/storybook-dark-mode#215]
Recently updated to storybook v7 with the latest version of `storybook-dark-mode`. In storybook v6, when clicking the dark mode toggle icon, the preview iframe node specified via the `classTarget` option would update the class of the element. In v7, this no longer happens.

No error message displays in the browser console. Has storybook v7 been tested with this library yet?

My config:

```
darkMode: {
  classTarget: 'html',
  stylePreview: true
},
```

**Comment by hipstersmoothie** [comment]
I don't think the plugin is working at all in v7. closing in favor #205

**Comment by redonkulus** [comment]
@hipstersmoothie most of the plugin works for me except this one issue. So I'm not sure its related to that other issue, I haven't seen that problem.
