### ISSUE TITLE
Custom themes not applied in the manager (Storybook 7/vitejs)

### ISSUE THREAD

**Issue by fauxparse** [hipstersmoothie/storybook-dark-mode#216]
I'm defining custom themes based on the default SB themes, but they're not being applied. In `preview.ts` I have:

```ts
export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  darkMode: {
    dark, // my dark theme
    light, // my light theme
  },
};
```

...but it's just applying the default SB light and dark themes. I can see by looking at `localStorage` that the default themes are being written there; clearing `localStorage` and restarting storybook doesn't help.

**Comment by hipstersmoothie** [comment]
In general this plugin doesn't work with v7 yet. closing in favor of #205
