### ISSUE TITLE
support adding multiple classes

### ISSUE THREAD

**Issue by unional** [hipstersmoothie/storybook-dark-mode#237]
The following causes error: `DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('host-dark app-dark') contains HTML space characters, which are not valid in tokens.`

```
darkMode: {
	current: 'host-dark app-dark', // initial mode
	darkClass: 'host-dark app-dark',
	stylePreview: true
}
```

We need this because we are working on MFE and each MFE using a different tailwind prefix (`app1`, `app2`, etc).

**Comment by hipstersmoothie** [comment]
If you want to make a PR to fix I'd be happy to merge

**Comment by unional** [comment]
It's actually support now that we can do `darkClass: ['host-dark', app-dark']`
