### ISSUE TITLE
How to add a style class to the story wrapper?

### ISSUE THREAD

**Issue by dtslvr** [hipstersmoothie/storybook-dark-mode#52]
Hello guys,

I'd like to simply add a style class to the story wrapper when toggling the dark mode (and remove it again). Can you please provide an example in Angular?

Thanks a lot!

**Comment by hipstersmoothie** [comment]
Here are the docs on how to do it in react 

https://github.com/hipstersmoothie/storybook-dark-mode#story-integration

basically you just need to do listen to the `DARK_MODE` event and do something angular-y

```js
channel.on('DARK_MODE', setDark);
```

**Comment by jpzwarte** [comment]
This is probably the same issue as #101 ?

**Comment by hipstersmoothie** [comment]
Yup! Closed via #102
