### ISSUE TITLE
Emit DARK_MODE when `storyRendered` is triggered

### ISSUE THREAD

**Issue by lindesvard** [hipstersmoothie/storybook-dark-mode#72]
Having issues when switching stories. We run storybook with `onDeviceUI: false` and when I switch story the app goes back to light mode. Tried to add `storyRendered` to your package and that solved it.

So now when I change story the new story gets the DARK_MODE event and the screen is dark.

Can make a PR if you want to get this in :)

**Comment by lindesvard** [comment]
To clarify, this is on `@storybook/react-native`

**Comment by hipstersmoothie** [comment]
@lindesvard PRs welcome!
