### ISSUE TITLE
Update to work with v5

### ISSUE THREAD

**Issue by stramel** [hipstersmoothie/storybook-dark-mode#8]
toggle not visible on v6

**Comment by hipstersmoothie** [comment]
@stramel V6 of what? the storybook alpha is only at 5.1, I don't see a 6

**Comment by stramel** [comment]
😅 ha, yeah, sorry v5

**Comment by hipstersmoothie** [comment]
Can i get a example repo? It should *only* work with v5 since that is when the toolbar was introduced

**Comment by carlesnunez** [comment]
I'm working with it in v5 and is working fine

**Comment by stramel** [comment]
Sorry, I no longer have time to create an example for this. Will close for now
