### ISSUE TITLE
Cannot set default mode to light

### ISSUE THREAD

**Issue by ashbuilds** [hipstersmoothie/storybook-dark-mode#86]
Hi, Im trying to set default mode to light but the option using `addParameter` with darkMode is not working. 

`addParameters({
  darkMode: {
    current: 'light'
  }
});`

Is it possible to change the default mode?

**Comment by valentinbourqui** [comment]
@ashbuilds  did you find a workaround ?

**Comment by hipstersmoothie** [comment]
This seems to be because we now respect the user's configured color mode preference on their OS. We can either have it one of two ways:

1. The `current` value is always respected => Doesn't respect system preferences, but a user could toggle to dark mode, refresh and still have dark mode set
2. The system preference is always respected => Doesn't use `current` if system has prefers-dark, user can still toggle

I'm leaning towards `2` as this seems to be the more common approach. As a dark mode user myself I would also want the storybook UI to respect my settings.

What are your thoughts @ashbuilds and @valentinbourqui? What would you expect the UI to do?

**Comment by hipstersmoothie** [comment]
I went with: If you set it then it overrides the system preference

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in `v0.4.1` :rocket:

**Comment by valentinbourqui** [comment]
Thank you it was exactly what I m thinking. I agree that take default preference is a very good idea when nothing is specified.  But in my case I'm currently using this dependency inside a private storybook just to show how components look with the dark mode and I want that by default light mode activated.

**Comment by hipstersmoothie** [comment]
Part of the design intent behind this plugin is that this is the dark theme for the **storybook UI**. Something that in my mind is a separate concept from viewing your components in a dark mode context.

As a dark mode user myself I always have the storybook UI in dark mode. While I use a knob to render my stories with a different color theme.

In our internal storybook this is how we do that

```js
// Add a global decorator that will render a dark background when the 
// "Color Scheme" knob is set to dark
addDecorator(function (storyFn) {
  // A knob for color scheme added to every story
  const colorScheme = select('Color Scheme', ['light', 'dark'], 'light');

  return React.createElement(ThemeProvider, {
    // A knob for theme added to every story
    theme: select('Theme', Object.keys(themes), 'default'),
    colorScheme,
    children: [
      React.createElement('style', {
        dangerouslySetInnerHTML: {
          __html: `html { ${
            colorScheme === 'dark' ? 'background-color: rgb(35,35,35);' : ''
          } }`,
        },
      }),
      storyFn(),
    ],
  });
});
```

**Comment by valentinbourqui** [comment]
Ok it make sense. I didn't think to use knobs to do this, it's a good idea and it works perfect thank you. :)

**Comment by OrkoHunter** [comment]
Hi @hipstersmoothie, I am not able to find how to import this `select` function.

```
  const colorScheme = select('Color Scheme', ['light', 'dark'], 'light');
```

Sorry if it's too obvious 🙇

**Comment by OrkoHunter** [comment]
On doing a search, I figured out that `select` is imported from `@storybook/addon-knobs`. Thanks! ❤️
