### ISSUE TITLE
Theme won't load if default Story is just MDX

### ISSUE THREAD

**Issue by tskarhed** [hipstersmoothie/storybook-dark-mode#94]
https://storage.googleapis.com/grafana-storybook/1751b1a/index.html?path=/story/docs-overview-intro--page

Navigating to another story triggers theme to load. Looking into this, might come with PR soon.

**Comment by tskarhed** [comment]
Conisder using `core-events` https://github.com/storybookjs/storybook/blob/next/lib/core-events/src/index.ts

**Comment by hipstersmoothie** [comment]
PRs welcome!

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in `v0.4.0` :rocket:
